# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donkidik.PostType'),
            preserve_default=False,
        ),
    ]
