# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donkidik', '0002_auto_20160712_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='donkidik.Post')),
                ('knots', models.IntegerField(blank=True, null=True)),
                ('gust', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 14, 10, 47, 1, 602614, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='donkidik.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donkidik.Spot'),
        ),
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='attending_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_meta', to='donkidik.Spot'),
        ),
    ]
