# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0004_auto_20160714_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 14, 10, 48, 44, 553309, tzinfo=utc)),
        ),
    ]
