# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0005_auto_20160714_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
