# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0006_auto_20160714_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_metas', to='donkidik.Spot'),
        ),
    ]
