# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0009_auto_20160730_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
