# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0012_auto_20160926_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'/static/avatars/default.jpg', upload_to=b'/static/avatars/'),
        ),
    ]
