# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0015_auto_20161002_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'/static/avatars/default.jpg', upload_to=b'static/avatars/'),
        ),
    ]
