# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import donkidik.models


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0016_auto_20161002_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'/static/avatars/default.jpg', upload_to=donkidik.models.user_dir),
        ),
    ]
