# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donkidik', '0017_auto_20161005_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
